In [1]:
import torch

## example#1
You must first identify the array, and then move that array as an
argument to the torch's Tensor process.

In [2]:
arr = [[ 3 , 4 ], [ 8 , 5 ]]
pyTensor = torch.Tensor(arr)
print(pyTensor)

tensor([[3., 4.],
        [8., 5.]])


## with the random number and all one
You must use the rand() method to construct a random number <br>
Tensor, and the ones() method of the torch to create a Tensor of all <br>
ones. Another torch tool, manual seed with 0 parameters, will be <br>
used with the rand to generate random numbers.

In [5]:
ones_t = torch.ones(( 2 , 2 ))
torch.manual_seed( 0 ) #to have same values for randomgeneration
rand_t = torch.rand(( 2 , 2 ))
print(ones_t)
print(rand_t)

tensor([[1., 1.],
        [1., 1.]])
tensor([[0.4963, 0.7682],
        [0.0885, 0.1320]])


## from numpy array
We must first construct a numpy array before we can create a <br>
Tensor from it. After you've built your numpy array, you'll need to <br>
pass it as an argument to from numpy(). The numpy array is <br>
converted to a Tensor using this form.

In [7]:
import numpy as np1
numpy_arr = np1.ones(( 2 , 2 ))
pyTensor = torch.from_numpy(numpy_arr)
np1_arr_from_Tensor = pyTensor.numpy()
print(np1_arr_from_Tensor)

[[1. 1.]
 [1. 1.]]
