## One Dimensional Tensors

우리 모두 알고 있듯이 PyTorch는 신경망 정의에 사용하기 쉽기 때문에  딥러닝 커뮤니티에서<br>
채택되었습니다. Tensor는 신경망의 핵심이며 PyTorch도 이를 중심으로 구축되었습니다. <br>
일반적으로 효율성이 크게 향상됩니다. 텐서는 가장 넓은 의미에서 행렬을 일반화한 것입니다. <br>

<img src=./images/oneDimTensors.png>

## Creating one-dimensional Tensor

The tensor property of the torch library is used to build a onedimensional <br>
Tensor. The torch.tensor() method is used to construct a tensor.

### Syntax

``` python
n=torch.tensor([Tensor elements])
```

## EXAMPLE

In [2]:
import torch

n=torch.tensor([1,2,3,4])
print(n)

tensor([1, 2, 3, 4])


## Checking data type

The data type of the element contained in Tensor can be verified. <br>
To determine the data form, we use Tensor's dtype() process.

In [3]:
print(n.dtype)

torch.int64


## Accessing of Tensor's elements

The index of a Tensor element can be used to access the elements <br>
of that Tensor. We can print the tensor variable if we want to print all <br>
of Tensor's components. Tensor index, like one-dimensional metrics <br>
index, begins at 0.

In [4]:
print(n[ 2 ])

tensor(3)


## Accessing of Tensor's elements
### with the specified range

By passing the beginning and ending indexes of elements separated <br>
by a colon, you can easily access elements within a given range (:). <br>
It will skip the first index element and print elements before the last <br>
index element is reached.

In [7]:
n=torch.tensor([1,2,3,4])
print(n[ 0 : 2 ])
print(n[0:])

tensor([1, 2])
tensor([1, 2, 3, 4])


## Creating of Floating Point Tensor
**using Integer elements**

Using integer components, we can make a floating point Tensor. <br>
The FloatTensor property of the torch is used in this.